# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "poetry.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install poetry
            poetry install

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "poetry.lock" }}

  test:
    docker:
      - image: circleci/python:3.8.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "poetry.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Don't run the graphical tests as they require human input.
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --ignore=tests/test_display tests


  black:
    # Complain if the code isn't blackened - https://github.com/ambv/black
    docker:
    # Image to run the tests in
      - image: circleci/python:3.8.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "poetry.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          command: |
            . venv/bin/activate
            black --check shimmer tests

  flake8:
    docker:
      # Image to run the tests in
      - image: circleci/python:3.8.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "poetry.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: # install and activate virtual environment with pip
          command: |
            . venv/bin/activate
            flake8 shimmer tests

  mypy:
    docker:
      # Image to run the tests in
      - image: circleci/python:3.8.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "poetry.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: # install and activate virtual environment with pip
          command: |
            . venv/bin/activate
            mypy shimmer tests

  pydocstyle:
    docker:
      # Image to run the tests in
      - image: circleci/python:3.8.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "poetry.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: # install and activate virtual environment with pip
          command: |
            . venv/bin/activate
            pydocstyle shimmer tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - black:
          requires:
            - build
      - flake8:
          requires:
            - build
      - mypy:
          requires:
            - build
      - pydocstyle:
          requires:
            - build
