name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install poetry
        uses: dschep/install-poetry-action@v1.3
        with:
          version: 1.0.0
          create_virtualenvs: true

      - name: Set PyPI token
        run: poetry config pypi-token.pypi ${PYPI_TOKEN}
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic   # Need an `id` for output variables
        with:
          branch: master
          extra_plugins: |
            @semantic-release/exec@3.3.8
            @semantic-release/git@7.0.18
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
