name: Test

on: [push]

jobs:

  black:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - run: |
          poetry run black --check shimmer tests

  flake8:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - run: |
          # The GitHub editor is 127 chars wide
          poetry run flake8 --count --max-line-length=127 --statistics shimmer tests

  mypy:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - run: |
          poetry run mypy shimmer tests

  pydocstyle:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - run: |
          poetry run pydocstyle shimmer tests

  pytest:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - run: |
          poetry run pytest tests
